// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0De3CLcXfRRKSPbuXp8mS_FL3mALZNig',
    appId: '1:821351982480:web:0b4693ee3ef9a3ff01bf15',
    messagingSenderId: '821351982480',
    projectId: 'chopnow-5110f',
    authDomain: 'chopnow-5110f.firebaseapp.com',
    storageBucket: 'chopnow-5110f.appspot.com',
    measurementId: 'G-Q4XEZKXRHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsQ2VxR7zU6JJ_q0Fy2Tpcc2D80cUH94c',
    appId: '1:821351982480:android:967d976b4cb09ae701bf15',
    messagingSenderId: '821351982480',
    projectId: 'chopnow-5110f',
    storageBucket: 'chopnow-5110f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCgiIChOFb79uwQt4JJBrOjpZuUL0Mzc0',
    appId: '1:821351982480:ios:7f0368296a7e4b1001bf15',
    messagingSenderId: '821351982480',
    projectId: 'chopnow-5110f',
    storageBucket: 'chopnow-5110f.appspot.com',
    iosBundleId: 'io.nobsafrica.rider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCgiIChOFb79uwQt4JJBrOjpZuUL0Mzc0',
    appId: '1:821351982480:ios:7f0368296a7e4b1001bf15',
    messagingSenderId: '821351982480',
    projectId: 'chopnow-5110f',
    storageBucket: 'chopnow-5110f.appspot.com',
    iosBundleId: 'io.nobsafrica.rider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0De3CLcXfRRKSPbuXp8mS_FL3mALZNig',
    appId: '1:821351982480:web:5883f1dc5f83a6d601bf15',
    messagingSenderId: '821351982480',
    projectId: 'chopnow-5110f',
    authDomain: 'chopnow-5110f.firebaseapp.com',
    storageBucket: 'chopnow-5110f.appspot.com',
    measurementId: 'G-YKCFXT3K43',
  );
}
